### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by pborreli**

### CODE REVIEW

**Comment by pborreli** [comment]
deadsleep

**Comment by Jerskouille** [comment]
Oh, wow, I'm sorry, this repository is actually automatically generated from our (currently closed-source) application docs.
Thanks for this effort, I'll fix them upstream! :)

**Comment by Jerskouille** [comment]
Fixed and deployed! Thanks again 💯 !

**Comment by pborreli** [comment]
thanks for sharing

**Pull request closed without merging**
